name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run:  GOOS=linux GOARCH=amd64 go build -o fairfood ./... 
    
  
    - name: Build and push docker container 
      run: |
       docker build . -t dmevanct/fairfood:$GITHUB_SHA
       docker push dmevanct/fairfood:$GITHUB_SHA

